server:
  port: 8084

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/final
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


feign:
  polygon-service-url: https://api.polygon.io
  name: PolygonServiceFeign
